import asyncio

class GRPCStreamManager:
    def __init__(self, endpoint: str):
        self.endpoint = endpoint
        self.stream_active = False
        
    async def connect(self):
        # In a real environment, establish aiogrpc channel
        self.stream_active = True
        
    async def listen(self):
        while self.stream_active:
            # Yield events generated by the chain
            await asyncio.sleep(0.1)
